#!/bin/bash

if [ "$(whoami)" != "root" ]; then
	echo "This script must be run as root (sudo)."
	exit 1
fi

mkdir -p /usr/local/bin
cp -i feen /usr/local/bin/feen
chmod 755 /usr/local/bin/feen
cp -i feen.png /usr/share/pixmaps/feen.png
chmod 644 /usr/share/pixmaps/feen.png

if ! [ -f "/usr/share/pixmaps/feen.png" -a -r "/usr/share/pixmaps/feen.png" -a -x "/usr/local/bin/feen" ] ; then
	echo "feen-linux install failed!"
else
	echo "feen-linux is now installed!"
fi
